### ISSUE TITLE
Compute secondary fields more efficiently

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#10]
This is an improvement to follow issue #9 

Develop an dependency engine so that we have some flag somewhere that records whether
  - m
  - H
  - or interaction terms
have changed since we computed interaction data last with OOMMF

If the user requests any of the computed interactions, we check whether we have cached data that is still up-to-date. If so, we return the cached data. If not, we call OOMMF to compute the interaction values.

Whenever we call OOMMF, we store all fields, energies and energy densities to disk and cache them.

This could be realised with the concept of 'virtual time'.

**Comment by mb1a15** [comment]
Do we still want this functionality or we prefer to keep the code lean and compute effective fields interactively (only when requested)? Introducing 'virtual time' will open many questions and complicate the code a lot. The only benefit would be to have cached fields. Also, this would mean that we compute and save all fields, densities, energies,... every time we run OOMMF and in more than 99% of cases we are not going to retrieve them.

**Comment by fangohr** [comment]
Happy to close this for now and keep the code lean. If we run into performance issues, we can reconsider this and other options.
