### ISSUE TITLE
Are we actually running the --nbval tests on travis? 

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#17]
Looks to me as if we are not. There is some duplication of commands in target "test-docker" and in .travis.yml, and the --nbval-lax command is in the Makefile target, but as far as I can see we are not actually calling that on Travis.

Suggested action: update so that Makefile target is used inside docker in .travis.yml.

**Comment by mb1a15** [comment]
nbval tests now run on Travis. The remaining thing is to remove nbval dependencies (ipykernel) after its pip version is updated.
