### ISSUE TITLE
std problem 5 test failing

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#24]
Just trying with the latest version as of now:

<pre>
import oommfc
oommfc.test()
</pre>
all tests pass, apart from this:
<pre>
============================================================================== FAILURES ==============================================================================
___________________________________________________________________________ test_stdprob5 ____________________________________________________________________________

    @pytest.mark.oommf
    def test_stdprob5():
        name = "stdprob5"

        # Remove any previous simulation directories.
        if os.path.exists(name):
            shutil.rmtree(name)

        # Geometry
        lx = 100e-9  # x dimension of the sample(m)
        ly = 100e-9  # y dimension of the sample (m)
        lz = 10e-9  # sample thickness (m)

        # Material (permalloy) parameters
        Ms = 8e5  # saturation magnetisation (A/m)
        A = 1.3e-11  # exchange energy constant (J/m)

        # Dynamics (LLG + STT equation) parameters
        gamma = 2.211e5  # gyromagnetic ratio (m/As)
        alpha = 0.1  # Gilbert damping
        ux = -72.35  # velocity in x direction
        beta = 0.05  # non-adiabatic STT parameter

        system = oc.System(name=name)
        mesh = oc.Mesh(p1=(0, 0, 0), p2=(100e-9, 100e-9, 10e-9),
                       cell=(5e-9, 5e-9, 5e-9))
        system.hamiltonian = oc.Exchange(A) + oc.Demag()

        def m_vortex(pos):
            x, y, z = pos[0]/1e-9-50, pos[1]/1e-9-50, pos[2]/1e-9
            return (-y, x, 10)

        system.m = df.Field(mesh, value=m_vortex, norm=Ms)

        md = oc.MinDriver()
        md.drive(system)

        system.dynamics += oc.Precession(gamma) + oc.Damping(alpha) + \
            oc.STT(u=(ux, 0, 0), beta=beta)

        td = oc.TimeDriver()
        td.drive(system, t=8e-9, n=100)

        mx = system.dt["mx"].as_matrix()

>       assert -0.03 < mx.max() < 0
E       assert 0.32890981244484879 < 0
E        +  where 0.32890981244484879 = <built-in method max of numpy.ndarray object at 0x11d7310d0>()
E        +    where <built-in method max of numpy.ndarray object at 0x11d7310d0> = array([-0.00585324,  0.07644325,  0.10511611,  0.14835181,  0.22632496,\n        0.27594319,  0.30758326,  0.32858074, ...587295,  0.20530587,  0.2046604 ,  0.20404881,\n        0.20356513,  0.20327149,  0.20319252,  0.2033168 ,  0.20360366]).max

oommfc/oommfc/tests/test_stdprob5.py:56: AssertionError
------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------
2017/7/21 9:12: Calling OOMMF (stdprob5/stdprob5.mif) ... [0.7s]
 <1> mmarchive killed
 <2> mmarchive killed
2017/7/21 9:12: Calling OOMMF (stdprob5/stdprob5.mif) ... [10.1s]
 <1> mmarchive killed
 <2> mmarchive killed
 <3> mmarchive killed
------------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------------
<86365> killoommf  Oc_Config warning:
Tcl version mismatch:
	/Users/fangohr/anaconda3/envs/joommf-dev2/lib/tclConfig.sh from 8.5.19
	Running Tcl 8.5.9
<86404> killoommf  Oc_Config warning:
Tcl version mismatch:
	/Users/fangohr/anaconda3/envs/joommf-dev2/lib/tclConfig.sh from 8.5.19
	Running Tcl 8.5.9
========================================================================= 3 tests deselected =========================================================================
======================================================== 1 failed, 126 passed, 3 deselected in 138.09 seconds ========================================================
</pre>

OOMMFC version used:
<pre>
commit 23c5baf96788e8d1c40dbdf5325d4216a658ddaa (HEAD -> master, origin/master, origin/HEAD)
Author: Thomas Kluyver <thomas@kluyver.me.uk>
Date:   Wed Jun 21 12:02:26 2017 +0100

    Change how we check for a conda environment on Windows
</pre>

**Comment by fangohr** [comment]
This problem has disappeared.

**Comment by marijanbeg** [comment]
This is the same issue as #32. Therefore, I am closing this issue.
