### ISSUE TITLE
sarge "no stderr" on windows issue

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#26]
We have an error [1] that only occurs [2] on windows. It seems to come down to a sarge object not having a 'stderr' attribute, where it would have this on Linux/OSX.

The line that actually raises the error is in this function: https://github.com/joommf/oommfc/blob/master/oommfc/oommf.py#L18

Could somebody with a windows environment and/or experience look into this, please? (maybe @rpep, @takluyver ) 

[1] https://ci.appveyor.com/project/conda-forge/oommfc-feedstock/build/1.0.3/job/3js9n9hwmxgjmu7t#L653
[2] https://github.com/conda-forge/oommfc-feedstock/pull/1

This bug prevents our updated conda-forge package for oommfc from being built (https://github.com/conda-forge/oommfc-feedstock/pull/1)

@marijanbeg - for information.

**Comment by takluyver** [comment]
[This code](https://github.com/joommf/oommfc/blob/master/oommfc/oommf.py#L75-L78) tells it to use `sarge.run` on Windows and `sarge.capture_both` on other platforms. I preserved that when I was refactoring the code to run oommf, because presumably someone thought it was necessary at some point, but I think it's causing this issue.

I'm not sure it's worth us using sarge over the standard subprocess module, which I'm more familiar with. The equivalent code using subprocess would look like this:

```python
from subprocess import run, PIPE
run(cmd, stdout=PIPE, stderr=PIPE)
```

**Comment by davidcortesortuno** [comment]
Running the tests in my Windows 8 machine with Anaconda 3, I don't get this error

![test](https://user-images.githubusercontent.com/12200541/32604076-2c4e114a-c544-11e7-997c-7767d976d0d9.png)

**Comment by rpep** [comment]
I noticed that in the [Sarge documentation](http://pythonhosted.org/sarge/overview.html#python-version-and-platform-compatibility) there's this:

```
Note For testing under Windows, you need to install the GnuWin32 coreutils package, and copy the relevant executables (currently libiconv2.dll, libintl3.dll, cat.exe, echo.exe, tee.exe, false.exe, true.exe, sleep.exe and touch.exe) to the directory from which you run the test harness (test_sarge.py)
```
Maybe it's something to do with how Sarge is installed?

@takluyver That was certainly the [approach I used](https://github.com/rpep/oommf-python/blob/master/joommf/oommfmif.py) in the "alpha" version, so I guess @marijanbeg had a good reason to move away from it?

**Comment by rpep** [comment]
Thomas and I have just noticed though that Sarge doesn't really seem to be getting updated - on PyPi the last release was in January 2015. So it might be a good idea to ditch it anyway.

**Comment by takluyver** [comment]
PR #27 would switch from sarge to subprocess.

**Comment by fangohr** [comment]
Many thanks, Thomas and Ryan. I am happy to switch to subprocess; I think we used `sarge` in the belief that it would be better than `subprocess`, but from PR #27 it appears that `subprocess` can be used just as well :) 

@marijanbeg - any objections to getting rid of sarge as in pull request 27?

**Comment by marijanbeg** [comment]
There was no particular reason why I chose to use `sarge`. It was mainly because it was easier and more convenient to use.
