### ISSUE TITLE
Test OOMMF setup with tiny test problem

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#7]
I have seen a case where the `oommf.tcl +version` worked fine but calling OOMMF didn't work for any real simulation work. This had to do with confusion about multiple Tk/Tcl versions installed on the system. It would be good to be able to detect this situation.

I propose that we have a tiny tiny micro magnetic problem that we can run for this purpose. For example a single cell (i.e. macro spin) run. We could even take problem where we know the analytic solution and compare the computed output (at very few data points) with that solution. 

This should be able to run very quickly, so that we can inject it in various places to see whether we are ready to embark on a larger calculations

**Comment by mb1a15** [comment]
This can be based on the new `bar` example in `oommfc/examples/bar.py`.

**Comment by marijanbeg** [comment]
This is now implemented in branch `refactor-oommf` (to be merged). A mif file is now part of the repository in `tests/test_files`.

**Comment by marijanbeg** [comment]
To be more explicit with this, the status of OOMMF is checked with

    import oommfc
    oommfc.oommf.status()

This prints the status and returns 0 if everything is ok and 1 if not.
