### ISSUE TITLE
system.m.plot_slice('x', 50e-9) displays and returns figure object

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#8]
A line like 

`system.m.plot_slice('x', 50e-9)` (as in the standard problem 3 example http://oommfc.readthedocs.io/en/latest/ipynb/standard_problem3.html), will display the figure twice:

Once because the actual plot_slice code displays it (I think - haven't looked at the code yet), the second time because the `plot_slice` command returns a figure object.

If we write `fig = system.m.plot_slice('x', 50e-9)`, then the figure is only displayed once (inside the notebook). But we could say 

`fig` 

in the next line, and that will display the figure.

I think my preference would be that 

`fig = system.m.plot_slice('x', 50e-9)`

will *not* display the figure, but just return the figure object. If the user wants to see it, they can either not assign the return value, i.e. 
`system.m.plot_slice('x', 50e-9,0)`, or assign it and ask the notebook to represent it in the next line, i.e.
<pre>
fig = system.m.plot_slice('x', 50e-9)
fig
</pre>

The situation where the figure is displayed twice is unsettling. I shall call it a bug (although it is partly a design question).

**Comment by mb1a15** [comment]
Duplicate: This issue is also raised in discretisedfield issue no.7. Therefore, I close this issue here.
