### ISSUE TITLE
Compute secondary fields interactively

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#9]
Step 1: implement this naively

Everytime `hamiltonian.INTERACTION.field`, or 
  `hamiltonian.INTERACTION.energy` or  `hamiltonian.INTERACTION.energy_density` is called, we execute OOMMF to retrieve that information and return it.

Disadvantages: lots of calling of OOMMF if we need multiple field values.

Issue #10 is (expected) to be a performance improvement on this.

**Comment by mb1a15** [comment]
This is now implemented on master.
